### ISSUE TITLE
[Question] How to limit size of image?

### ISSUE THREAD

**Issue by paw-lu** [jsbueno/terminedia#24]
Trying to use this library to convert images to block characters. So far it's working great.

One point of confusion for me is how to control the size of the output. For context, I'm trying to preserve the ratio of the image, but constrain either its height or width so that it can fit within an arbitrary space.

Here I attempt—and fail—to read in an image and constrain its output to 30 characters in width.

```python
import io

import terminedia
from PIL import Image

screen = terminedia.Screen(backend="ANSI")
resolution = "square"
size = terminedia.V2(x=30, y=30)

image = Image.open("Ent_Steven-Universe_SOCIAL.jpeg")
img = terminedia.shape(
    image,
    size=size,
    promote=True,
    resolution=resolution,
)
output = io.StringIO()
img.render(output=output, backend="ANSI")

print(output.getvalue())
print("-" * 30)  # Ruler to visualize 30 units across 
```

<img width="417" alt="Screen Shot 2021-08-20 at 8 08 15 PM" src="https://user-images.githubusercontent.com/30049606/130308608-bab377d4-2be0-479d-a1be-e58f19b69a43.png">

It renders perfectly, but is wider than 30 characters.

I'm trying to understand:

1. What does the `size` argument actually do? The resulting image is not 30x30.
2. What's the best way to accomplish my goal—preserving the original aspect ratio of an image while restraining the height and the width to be within a certain number of characters?

---

(Again) thanks for the project!

**Comment by paw-lu** [comment]
Follow up:

Tried different `resolution` values for the same `x` and `y` values in `size`, and get different sizes and aspect ratios.

Why is this the case?

<img width="991" alt="Screen Shot 2021-08-21 at 3 42 56 PM" src="https://user-images.githubusercontent.com/30049606/130336579-d14bae04-4991-481d-8a3f-addd105a4e7e.png">

**Comment by jsbueno** [comment]
The code would try to keep the aspect ratio of the source  image, no matter what "size" was passed. (but, when using any resolution other than "square" the aspect ratio of the terminal is 1:2, so all images would look-like broken). 
I just updated that code to respect the given size, and keep the aspect-ratio if one of the size components is set to "None"

**Comment by paw-lu** [comment]
> but, when using any resolution other than "square" the aspect ratio of the terminal is 1:2, so all images would look-like broken

Got it. Thanks for the explanation!

> I just updated that code to respect the given size, and keep the aspect-ratio if one of the size components is set to "None".

Thanks! It's appreciated. I look forward to trying it out!

**Comment by paw-lu** [comment]
[Just integrated the changes](https://github.com/paw-lu/nbpreview/pull/231) and wanted to say thanks for helping me out!
